### ISSUE TITLE
Some remarks and observations 

### ISSUE THREAD

**Issue by MuratovAS** [Rouji/single_php_filehost_docker#3]
good day
1) I think you should assign the `files` directory as `volume`
2) Do chmod/chown against `files` in `entry.sh`

A number of these edits will automatically create a `docker volume`, even if the user did not explicitly specify it at startup. This will allow you to recreate the container without losing files.

I also ran into the problem that my `/path/to/files` directory was not writable from the php/container. Never encountered this before.

**Comment by Rouji** [comment]
Yep, makes sense. I'll have a look at volumes and stuff.
tbh I'm not a docker guy, I just shat this together because someone kinda asked me to.

**Comment by Rouji** [comment]
@MuratovAS something like 12fbc1198b917ff8e88cdee1e072abd0a80a7583 and b87c8902de5fa88bb8436ea18fcb981ce13e0a5d, I guess?

**Comment by MuratovAS** [comment]
yes, that's what I was talking about. I think now everything is in order with the container. Thanks for supporting the project.
